name: ServerChannels
main: ServerChannels\ServerChannels
version: 2.3
api: [3.0.0]
load: STARTUP
author: EvolSoft
description: A powerful chat channelling plugin for PocketMine-MP
website: https://www.evolsoft.tk

commands:
 serverchannels:
   aliases: [serverch, sch]
   description: ServerChannels commands.
   permission: serverchannels
   
permissions:
 serverchannels:
  default: true
  description: ServerChannels permissions.
  children:
   serverchannels.channels:
    default: true
    description: ServerChannels channels permissions.
   serverchannels.commands:
    default: true
    description: ServerChannels commands permissions.
    children:
      serverchannels.commands.create:
       default: op
       description: ServerChannels command New permission.
      serverchannels.commands.help:
       default: true
       description: ServerChannels command Help permission.
      serverchannels.commands.info:
       default: op
       description: ServerChannels command Info permission.
      serverchannels.commands.reload:
       default: op
       description: ServerChannels command Reload permission.
      serverchannels.commands.list:
       default: op
       description: ServerChannels command List permission.
      serverchannels.commands.join:
       default: op
       description: ServerChannels command Join permission.
      serverchannels.commands.leave:
       default: op
       description: ServerChannels command Leave permission.
